openapi: 3.0.3
info:
  title: Common API Specification
  version: 1.0.0
  description: Common headers and objects for all DIGIT specifications.

paths: {}

components:
  parameters:
    
    RequestIdHeader:
      name: X-Request-ID
      in: header
      required: false
      description: "Unique identifier for tracking each request. Helps in debugging logs."
      schema:
        type: string
        minLength: 2
        maxLength: 64
        example: "req-12345-abcd"

    CorrelationIdHeader:
      name: X-Correlation-ID
      in: header
      required: false
      description: "Used for distributed tracing across multiple services."
      schema:
        type: string
        minLength: 2
        maxLength: 64
        example: "corr-67890-xyz"

    UserAgentHeader:
      name: User-Agent
      in: header
      required: false
      description: "Identifies the client making the request (browser, mobile app, etc.)."
      schema:
        type: string
        minLength: 5
        maxLength: 64
        example: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"

    TenantIdHeader:
      name: X-Tenant-ID
      in: header
      required: true
      description: "Identifies the tenant making the request. Required in multi-tenant systems."
      schema:
        type: string
        minLength: 2
        maxLength: 64
        example: "tenant-xyz"

    ForwardedForHeader:
      name: X-Forwarded-For
      in: header
      required: false
      description: "Client IP address (used for tracing in load-balanced environments)."
      schema:
        type: string
        minLength: 2
        maxLength: 64
        example: "192.168.1.1"
    
    ClientId:
      name: X-Client-Id
      in: header
      required: false
      description: "Unique identifier assigned to the client making the request."
      schema:
        type: string
        minLength: 3
        maxLength: 100
        example: "User-Admin-Client"

    ClientSecret:
      name: X-Client-Secret
      in: header
      required: false
      description: "Secret key used to authenticate the client making the request."
      schema:
        type: string
        minLength: 8
        maxLength: 256
        example: "s3cr3tK3y123"

    TimeStamp:
      name: X-Time-Stamp
      in: header
      required: false
      description: "Epoch timestamp (in milliseconds) indicating when the request was made."
      schema:
        type: integer
        minimum: 1000000000000
        maximum: 9999999999999
        example: 1712830200000
        
    RateLimit:
      name: X-RateLimit
      in: header
      required: false
      description: "Indicates the maximum number of allowed requests in a given timeframe."
      schema:
        type: integer
        minimum: 1
      example: 1000

    RateLimit-Remaining:
      name: X-RateLimit-Remaining
      in: header
      required: false
      description: "Indicates the remaining number of requests in the current rate limit window."
      schema:
        type: integer
        minimum: 0
      example: 999

    RateLimit-Reset:
      name: X-RateLimit-Reset
      in: header
      required: false
      description: "Indicates the time (in UTC epoch seconds) when the rate limit will reset."
      schema:
        type: integer
        minimum: 0
      example: 1701237890

  

  schemas:
    
    AuditDetails:
      type: object
      description: "Contains audit details, tracking record creation, modification, and deletion events."
      properties:
        createdBy:
          type: string
          description: "UUID of the user or system that created the record."
          example: "550e8400-e29b-41d4-a716-446655440000"
        createdTime:
          type: integer
          format: int64
          description: "Timestamp (epoch milliseconds) when the record was created."
          example: 1701234567890
        lastModifiedTime:
          type: integer
          format: int64
          description: "Timestamp (epoch milliseconds) when the record was last modified."
          example: 1701237890123
          
    Address:
      type: object
      properties:
        tenantId:
          type: string
          description: "Tenant unique identifier."
          example: "tenant-123"
        addressId:
          type: string
          readOnly: true
          description: "Unique ID for the address."
          example: "ADDR-5678"
        streetAddress:
          type: string
          description: "Full street address (house number, road, building)."
          example: "221B Baker Street"
        area:
          type: string
          description: "Locality or zone."
          example: "Marylebone"
        city:
          type: string
          description: "City name."
          example: "London"
        state:
          type: string
          description: "State or province."
          example: "Greater London"
        countryCode:
          type: string
          description: "ISO 3166-1 alpha-2 country code."
          example: "GB"
        pincode:
          type: string
          description: "ZIP or postal code."
          example: "NW1 6XE"
        landmark:
          type: string
          description: "Nearby landmark for reference."
          example: "Near Regent's Park"
        geoLocation:
          type: object
          description: "Latitude and longitude of the address."
          properties:
            latitude:
              type: number
              format: double
              description: "Geographical latitude."
              example: 51.523767
            longitude:
              type: number
              format: double
              description: "Geographical longitude."
              example: -0.1585557
    
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: "Module-specific error code."
          example: "User.NotFound"
        message:
          type: string
          description: "Readable error message."
          example: "User not found."
        description:
          type: string
          description: "Optional long description for debugging."
        params:
          type: array
          description: "Optional placeholders for dynamic messages."
          items:
            type: string
              
              
              
